2018-02-26 19:01:33,547 ERROR exception 6640 Internal Server Error: /request_friend/
Traceback (most recent call last):
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/adrian/skyfolk/user_profile/views.py", line 675, in request_friend
    m = Profile.objects.get(user_id=slug)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/query.py", line 371, in get
    clone = self.filter(*args, **kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/query.py", line 784, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/query.py", line 802, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1250, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1276, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1206, in build_filter
    condition = lookup_class(lhs, value)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/fields/related_lookups.py", line 112, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 966, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: '1123fasf'
2018-02-26 19:01:35,486 ERROR exception 6640 Internal Server Error: /remove_relationship/
Traceback (most recent call last):
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/adrian/skyfolk/user_profile/views.py", line 817, in remove_relationship
    profile_user = Profile.objects.get(user_id=slug)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/query.py", line 371, in get
    clone = self.filter(*args, **kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/query.py", line 784, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/query.py", line 802, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1250, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1276, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1206, in build_filter
    condition = lookup_class(lhs, value)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/fields/related_lookups.py", line 112, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 966, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: '1123fasf'
2018-02-26 19:02:45,315 ERROR exception 6804 Internal Server Error: /request_friend/
Traceback (most recent call last):
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/adrian/skyfolk/user_profile/views.py", line 675, in request_friend
    m = Profile.objects.get(user_id=slug)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/query.py", line 371, in get
    clone = self.filter(*args, **kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/query.py", line 784, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/query.py", line 802, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1250, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1276, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1206, in build_filter
    condition = lookup_class(lhs, value)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/fields/related_lookups.py", line 112, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 966, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: '1123fasf'
2018-02-26 19:02:47,274 ERROR exception 6804 Internal Server Error: /remove_relationship/
Traceback (most recent call last):
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/adrian/skyfolk/user_profile/views.py", line 817, in remove_relationship
    profile_user = Profile.objects.get(user_id=slug)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/query.py", line 371, in get
    clone = self.filter(*args, **kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/query.py", line 784, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/query.py", line 802, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1250, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1276, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1206, in build_filter
    condition = lookup_class(lhs, value)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/fields/related_lookups.py", line 112, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 966, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: '1123fasf'
2018-02-26 19:04:52,225 ERROR exception 6905 Internal Server Error: /request_friend/
Traceback (most recent call last):
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/adrian/skyfolk/user_profile/views.py", line 675, in request_friend
    m = Profile.objects.get(user_id=slug)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/query.py", line 371, in get
    clone = self.filter(*args, **kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/query.py", line 784, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/query.py", line 802, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1250, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1276, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1206, in build_filter
    condition = lookup_class(lhs, value)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/fields/related_lookups.py", line 112, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 966, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: '1123fasf'
2018-02-26 19:04:54,210 ERROR exception 6905 Internal Server Error: /remove_relationship/
Traceback (most recent call last):
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/adrian/skyfolk/user_profile/views.py", line 817, in remove_relationship
    profile_user = Profile.objects.get(user_id=slug)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/query.py", line 371, in get
    clone = self.filter(*args, **kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/query.py", line 784, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/query.py", line 802, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1250, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1276, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1206, in build_filter
    condition = lookup_class(lhs, value)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/fields/related_lookups.py", line 112, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 966, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: '1123fasf'
2018-02-26 19:05:20,717 ERROR exception 6986 Internal Server Error: /request_friend/
Traceback (most recent call last):
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/adrian/skyfolk/user_profile/views.py", line 675, in request_friend
    m = Profile.objects.get(user_id=slug)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/query.py", line 371, in get
    clone = self.filter(*args, **kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/query.py", line 784, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/query.py", line 802, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1250, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1276, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1206, in build_filter
    condition = lookup_class(lhs, value)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/fields/related_lookups.py", line 112, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 966, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: '1123fasf'
2018-02-26 19:05:22,567 ERROR exception 6986 Internal Server Error: /remove_relationship/
Traceback (most recent call last):
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/adrian/skyfolk/user_profile/views.py", line 817, in remove_relationship
    profile_user = Profile.objects.get(user_id=slug)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/query.py", line 371, in get
    clone = self.filter(*args, **kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/query.py", line 784, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/query.py", line 802, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1250, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1276, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1206, in build_filter
    condition = lookup_class(lhs, value)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/fields/related_lookups.py", line 112, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 966, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: '1123fasf'
2018-02-26 19:05:55,058 ERROR exception 7060 Internal Server Error: /request_friend/
Traceback (most recent call last):
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/adrian/skyfolk/user_profile/views.py", line 675, in request_friend
    m = Profile.objects.get(user_id=slug)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/query.py", line 371, in get
    clone = self.filter(*args, **kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/query.py", line 784, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/query.py", line 802, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1250, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1276, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1206, in build_filter
    condition = lookup_class(lhs, value)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/fields/related_lookups.py", line 112, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 966, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: '1123fasf'
2018-02-26 19:05:56,962 ERROR exception 7060 Internal Server Error: /remove_relationship/
Traceback (most recent call last):
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/adrian/skyfolk/user_profile/views.py", line 817, in remove_relationship
    profile_user = Profile.objects.get(user_id=slug)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/query.py", line 371, in get
    clone = self.filter(*args, **kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/query.py", line 784, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/query.py", line 802, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1250, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1276, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1206, in build_filter
    condition = lookup_class(lhs, value)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/fields/related_lookups.py", line 112, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 966, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: '1123fasf'
2018-02-26 19:09:10,285 ERROR exception 7400 Internal Server Error: /request_friend/
Traceback (most recent call last):
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/adrian/skyfolk/user_profile/views.py", line 675, in request_friend
    m = Profile.objects.get(user_id=slug)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/query.py", line 371, in get
    clone = self.filter(*args, **kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/query.py", line 784, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/query.py", line 802, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1250, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1276, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1206, in build_filter
    condition = lookup_class(lhs, value)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/fields/related_lookups.py", line 112, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 966, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: '1123fasf'
2018-02-26 19:09:12,314 ERROR exception 7400 Internal Server Error: /remove_relationship/
Traceback (most recent call last):
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/adrian/skyfolk/user_profile/views.py", line 817, in remove_relationship
    profile_user = Profile.objects.get(user_id=slug)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/query.py", line 371, in get
    clone = self.filter(*args, **kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/query.py", line 784, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/query.py", line 802, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1250, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1276, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1206, in build_filter
    condition = lookup_class(lhs, value)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/fields/related_lookups.py", line 112, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 966, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: '1123fasf'
2018-02-26 19:10:18,963 ERROR exception 7542 Internal Server Error: /request_friend/
Traceback (most recent call last):
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/adrian/skyfolk/user_profile/views.py", line 675, in request_friend
    m = Profile.objects.get(user_id=slug)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/query.py", line 371, in get
    clone = self.filter(*args, **kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/query.py", line 784, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/query.py", line 802, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1250, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1276, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1206, in build_filter
    condition = lookup_class(lhs, value)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/fields/related_lookups.py", line 112, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 966, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: '1123fasf'
2018-02-26 19:10:21,463 ERROR exception 7542 Internal Server Error: /remove_relationship/
Traceback (most recent call last):
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/adrian/skyfolk/user_profile/views.py", line 817, in remove_relationship
    profile_user = Profile.objects.get(user_id=slug)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/query.py", line 371, in get
    clone = self.filter(*args, **kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/query.py", line 784, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/query.py", line 802, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1250, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1276, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1206, in build_filter
    condition = lookup_class(lhs, value)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/fields/related_lookups.py", line 112, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 966, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: '1123fasf'
2018-02-26 19:10:52,451 ERROR exception 7628 Internal Server Error: /request_friend/
Traceback (most recent call last):
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/adrian/skyfolk/user_profile/views.py", line 675, in request_friend
    m = Profile.objects.get(user_id=slug)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/query.py", line 371, in get
    clone = self.filter(*args, **kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/query.py", line 784, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/query.py", line 802, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1250, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1276, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1206, in build_filter
    condition = lookup_class(lhs, value)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/fields/related_lookups.py", line 112, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 966, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: '1123fasf'
2018-02-26 19:10:54,212 ERROR exception 7628 Internal Server Error: /remove_relationship/
Traceback (most recent call last):
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/adrian/skyfolk/user_profile/views.py", line 817, in remove_relationship
    profile_user = Profile.objects.get(user_id=slug)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/query.py", line 371, in get
    clone = self.filter(*args, **kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/query.py", line 784, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/query.py", line 802, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1250, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1276, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1206, in build_filter
    condition = lookup_class(lhs, value)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/fields/related_lookups.py", line 112, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 966, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: '1123fasf'
2018-02-26 19:11:38,014 ERROR exception 7735 Internal Server Error: /request_friend/
Traceback (most recent call last):
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/adrian/skyfolk/user_profile/views.py", line 675, in request_friend
    m = Profile.objects.get(user_id=slug)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/query.py", line 371, in get
    clone = self.filter(*args, **kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/query.py", line 784, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/query.py", line 802, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1250, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1276, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1206, in build_filter
    condition = lookup_class(lhs, value)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/fields/related_lookups.py", line 112, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 966, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: '1123fasf'
2018-02-26 19:11:39,690 ERROR exception 7735 Internal Server Error: /remove_relationship/
Traceback (most recent call last):
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/adrian/skyfolk/user_profile/views.py", line 817, in remove_relationship
    profile_user = Profile.objects.get(user_id=slug)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/query.py", line 371, in get
    clone = self.filter(*args, **kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/query.py", line 784, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/query.py", line 802, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1250, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1276, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1206, in build_filter
    condition = lookup_class(lhs, value)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/fields/related_lookups.py", line 112, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 966, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: '1123fasf'
2018-02-26 19:12:43,994 ERROR exception 7878 Internal Server Error: /request_friend/
Traceback (most recent call last):
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/adrian/skyfolk/user_profile/views.py", line 675, in request_friend
    m = Profile.objects.get(user_id=slug)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/query.py", line 371, in get
    clone = self.filter(*args, **kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/query.py", line 784, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/query.py", line 802, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1250, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1276, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1206, in build_filter
    condition = lookup_class(lhs, value)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/fields/related_lookups.py", line 112, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/home/adrian/.virtualenvs/skyfolk-ekQwuX29/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 966, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: '1123fasf'
